# Whether to check for updates on server startup
check-updates-on-start: true

# To learn how to configure plugins that are on different platforms check out the wiki: https://github.com/OakLoaf/PluginUpdater/wiki/PluginUpdater-Plugin
plugins:
  PluginUpdater:
    platform: modrinth
    modrinth-project-id: "IBSpJfbm"
    featured-only: true
  ExamplePlugin:
    enabled: false

messages:
  unchecked-color: "&8"
  update-available-color: "&#ffda54"
  major-update-available-color: "&#ff6969"
  update-prepared-color: "&#ffda54"
  latest-version-color: "&#b7faa2"
  updates-available: "&#e0c01b%amount% &#ffe27aupdates are available, type &#e0c01b'%updates_command%' &#ffe27afor more information!"
