name: PluginUpdater
version: '${version}'
main: org.lushplugins.pluginupdater.PluginUpdater
api-version: '1.18'
modrinth-project-id: "plugin-updater"
commands:
  pluginupdater:
    description: PluginUpdater Main Command
    usage: /pluginupdater
    aliases:
      - updater
  pluginupdates:
    description: Check for plugin updates
    usage: /pluginupdates
    aliases:
      - updates