name: Build Platform

on:
  workflow_call:
    inputs:
      gradle-tasks:
        required: true
        type: string
      display-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle Environment
        uses: ./.github/actions/setup-gradle.yml

      - name: ${{ inputs.display-name }}
        run: ./gradlew ${{ inputs.gradle-tasks }}