name: Run PR Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Prepare gradle
        run: |
          chmod +x ./gradlew

      - name: Build common:api
        run: |
          ./gradlew common:api:shadowJar

      - name: Build common:impl
        run: |
          ./gradlew common:impl:shadowJar
  build-paper:
    runs-on: ubuntu-latest
    needs: build-common
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Prepare gradle
        run: |
          chmod +x ./gradlew

      - name: Build paper:api
        run: |
          ./gradlew platform:paper:api:shadowJar

      - name: Build paper:plugin
        run: |
          ./gradlew platform:paper:plugin:shadowJar
  build-velocity:
    runs-on: ubuntu-latest
    needs: build-common
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Prepare gradle
        run: |
          chmod +x ./gradlew

      - name: Build velocity:plugin
        run: |
          ./gradlew platform:velocity:plugin:shadowJar
  check-success:
    runs-on: ubuntu-latest
    needs:
      - build-common
      - build-paper
      - build-velocity
    steps:
      - run: echo All builds successfully compiled