name: Run PR Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-common:
    name: 'Build common modules'
    uses: ./.github/workflows/build-platform.yml
    with:
      display-name: 'Build common modules'
      gradle-tasks: 'common:api:build common:impl:build'

  build-paper:
    name: 'Build Paper modules'
    needs: build-common
    if: always()
    uses: ./.github/workflows/build-platform.yml
    with:
      display-name: 'Build Paper modules'
      gradle-tasks: 'platform:paper-api:build platform:paper-plugin:build'

  build-velocity:
    name: 'Build Velocity modules'
    needs: build-common
    if: always()
    uses: ./.github/workflows/build-platform.yml
    with:
      display-name: 'Build Velocity modules'
      gradle-tasks: 'platform:velocity-plugin:build'